<?php
define( "DEALTYPE_BASE_TYPE", 0);
define( "DEALTYPE_ADDCOIN",1);
define( "DEALTYPE_TASKPASS_ADDCOIN",2);
define( "DEALTYPE_USETOOL",3);
define( "DEALTYPE_BUYTOOL_COIN",4);
define( "DEALTYPE_BUYTOOL_DIAMOND",5);
define( "DEALTYPE_GET_GIFT",6);
define( "DEALTYPE_USETOOL_OPENTASK",7);
define( "DEALTYPE_GET_GFIT_ADD_COIN",8);
define( "DEALTYPE_GET_GIFT_GET_ITEM",9);
define( "DEALTYPE_GET_GIFT_GET_CARD",10);
define( "DEALTYPE_GET_VIP_GIFT",11);
define( "DEALTYPE_GET_VIP_GIFT_ITEM",12);
define( "DEALTYPE_GET_VIP_GIFT_COIN",13);
define( "DEALTYPE_GET_QUEST_ITEMS",14);
